
services:
  web:
    container_name: flask_web

    build:
      context: ./flask
    ports:
      - "5001:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/flaskdb
    depends_on:
      - db
    volumes:
      - ./flask/logs:/app/logs



  db:
    container_name: flask_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
