version: "3.8"

services:
  web:
    build:
      context: ./flask
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/flaskdb
    depends_on:
      - db
    volumes:
      - ./flask/logs:/app/logs

  react:
    build:
      context: ./ReactJS
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "start"]
    volumes:
      - ./ReactJS:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - web

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
