version: '3.9'

services:
  web:
    build: .
    ports:
      - "5002:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@10.12.40.23:5432/postgres
    depends_on:
      - db
      - test-db 
    

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: testdb
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  test_postgres_data: 
